databases:
  - name: cjteste-db
    databaseName: provedordb
    user: user
    plan: free

services:
  - type: web
    name: cjteste-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cjteste-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
