"""initial

Revision ID: a77364a19b6b
Revises:
Create Date: 2026-06-12 13:35:18.239296

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a77364a19b6b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("documento", sa.String(), nullable=True),
        sa.Column("documento_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clientes_documento"), "clientes", ["documento"], unique=True
    )
    op.create_index(op.f("ix_clientes_email"), "clientes", ["email"], unique=True)
    op.create_index(op.f("ix_clientes_id"), "clientes", ["id"], unique=False)
    op.create_table(
        "planos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=True),
        sa.Column("preco", sa.Float(), nullable=True),
        sa.Column("velocidade_mbps", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_planos_id"), "planos", ["id"], unique=False)
    op.create_index(op.f("ix_planos_nome"), "planos", ["nome"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_planos_nome"), table_name="planos")
    op.drop_index(op.f("ix_planos_id"), table_name="planos")
    op.drop_table("planos")
    op.drop_index(op.f("ix_clientes_id"), table_name="clientes")
    op.drop_index(op.f("ix_clientes_email"), table_name="clientes")
    op.drop_index(op.f("ix_clientes_documento"), table_name="clientes")
    op.drop_table("clientes")
    # ### end Alembic commands ###
