schema: spec-driven
# Project context (optional)
# This is shown to AI when creating artifacts.
# Add your tech stack, conventions, style guides, domain knowledge, etc.
# Example:
#   context: |
#     Tech stack: TypeScript, React, Node.js
#     We use conventional commits
#     Domain: e-commerce platform

# Per-artifact rules (optional)
# Add custom rules for specific artifacts.
# Example:
#   rules:
#     proposal:
#       - Keep proposals under 500 words
#       - Always include a "Non-goals" section
#     tasks:
#       - Break tasks into chunks of max 2 hours
context:
  Por favor, gere todos os artefatos em Português-BR.

  # TECH STACK - BACKEND
  -Framework: FastAPI
  -Banco de dados: PostgreSQL
  - Autenticação: JWT
  - ORM: SQLAlchemy
  -Validação: Pydantic
  
  #TECH STACK - FRONTEND
  -Framework: React
  -Linguagem: TypeScript
  -Estilo: TailwindCSS  
  -Componentes: shadcn/ui

  #DOMAIN
  -Tipo: O projeto é um MP para fluxo de autoatendimento de um provedor de internet
  
  rules:
    proposal:
      -Toda nova proposta deve especificar claramente os objetivos, não-objetivos e decisões que serão tomadas.
  specs:
    - Use sempre o formato Gioven/When/Then (Dado/Quando/Então) para descrever os cenários.
  
  design:
    - BACKEND:Detalha os modelos do banco de dados (PostgreSQL) e como o schema do FastAPI/Pydantic garante o Type-safety ponta a ponta.
    - Frontend: Detalha os componentes do shadcn/ui que serão utilizados e como o Next.js será utilizado para criar o dashboard
    tasks:
    - Sempre inclua tarefas que viabilizem o TDD (Desenvolvimento orientado por testes), ou seja, primeiro deve-se criar o teste, para depois criar a funcionalidade definida.
    - Mantenha os itens pequenos, sequenciais e fáceis de serem implementados em uma única sessão de trabalho.
 
  